FinalProject2/FinalProject2/Controllers/CongViecController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FinalProject2.Models;

namespace FinalProject2.Controllers
{
    [Authorize]
    public class CongViecController : Controller
    {
        private FinalProjectDbContext db = new FinalProjectDbContext();

        //
        // GET: /CongViec/

        public ActionResult Index()
        {
            return View(db.CongViecs.ToList());
        }

        //
        // GET: /CongViec/Details/5

        public ActionResult Details(int id = 0)
        {
            CongViec congviec = db.CongViecs.Find(id);
            if (congviec == null)
            {
                return HttpNotFound();
            }
            return View(congviec);
        }

        //
        // GET: /CongViec/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /CongViec/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CongViec congviec)
        {
            if (ModelState.IsValid)
            {
                int iduser = db.UserProfiles.Where(m => m.UserName == User.Identity.Name).Single().UserId;
                congviec.UserProfileUserId = iduser;
    
                db.CongViecs.Add(congviec);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(congviec);
        }

        //
        // GET: /CongViec/Edit/5

        public ActionResult Edit(int id = 0)
        {
            CongViec congviec = db.CongViecs.Find(id);
            if (congviec == null)
            {
                return HttpNotFound();
            }
            return View(congviec);
        }

        //
        // POST: /CongViec/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(CongViec congviec)
        {
            if (ModelState.IsValid)
            {
                db.Entry(congviec).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(congviec);
        }

        //
        // GET: /CongViec/Delete/5

        public ActionResult Delete(int id = 0)
        {
            CongViec congviec = db.CongViecs.Find(id);
            if (congviec == null)
            {
                return HttpNotFound();
            }
            return View(congviec);
        }

        //
        // POST: /CongViec/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CongViec congviec = db.CongViecs.Find(id);
            db.CongViecs.Remove(congviec);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

FinalProject2/FinalProject2/Controllers/ThongTinCaNhanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FinalProject2.Models;
using System.Data.Entity;
using System.Data;

namespace FinalProject2.Controllers
{
    [Authorize]
    public class ThongTinCaNhanController : Controller
    {
        //
        // GET: /ThongTinCaNhan/

       private  FinalProjectDbContext db = new FinalProjectDbContext();
       public ActionResult Index()
       {
           return View(db.UserProfiles.ToList());
       }
        //
        // GET: /ThongTinCaNhan/Details/5

        public ActionResult Details(int id = 0)
        {
           UserProfile thongtin = db.UserProfiles.Find(id);
            if (thongtin == null)
            {
                return HttpNotFound();
            }
            return View(thongtin);
        }

        //
        // GET: /TroGiup/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /TroGiup/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(UserProfile thongtin)
        {
            if (ModelState.IsValid)
            {
                db.UserProfiles.Add(thongtin);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(thongtin);
        }

        //
        // GET: /TroGiup/Edit/5

        public ActionResult Edit(int id = 0)
        {
            UserProfile thongtin = db.UserProfiles.Find(id);
            if (thongtin == null)
            {
                return HttpNotFound();
            }
            return View(thongtin);
        }

        //
        // POST: /TroGiup/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(UserProfile thongtin)
        {
            if (ModelState.IsValid)
            {
                db.Entry(thongtin).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(thongtin);
        }

        //
        // GET: /TroGiup/Delete/5

        public ActionResult Delete(int id = 0)
        {
            UserProfile thongtin = db.UserProfiles.Find(id);
            if (thongtin == null)
            {
                return HttpNotFound();
            }
            return View(thongtin);
        }

        //
        // POST: /TroGiup/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            UserProfile thongtin = db.UserProfiles.Find(id);
            db.UserProfiles.Remove(thongtin);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
     }
   
  
}

FinalProject2/FinalProject2/Controllers/TrangChuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FinalProject2.Models;
using System.Data.Entity;
namespace FinalProject2.Controllers
{
    [Authorize]
    public class TrangChuController : Controller
    {
        //
        // GET: /TrangChu/
        FinalProjectDbContext db = new FinalProjectDbContext(); 
        public ActionResult Index()
        {
            int iduser = db.UserProfiles.Where(m => m.UserName == User.Identity.Name).Single().UserId;
            return View(db.UserProfiles.Find(iduser));
        }

    }
}

FinalProject2/FinalProject2/Controllers/TroGiupController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FinalProject2.Models;

namespace FinalProject2.Controllers
{
    
    public class TroGiupController : Controller
    {
        private FinalProjectDbContext db = new FinalProjectDbContext();

        //
        // GET: /TroGiup/

        public ActionResult Index()
        {
            return View(db.TroGiup.ToList());
        }

        //
        // GET: /TroGiup/Details/5

        public ActionResult Details(int id = 0)
        {
            TroGiup trogiup = db.TroGiup.Find(id);
            if (trogiup == null)
            {
                return HttpNotFound();
            }
            return View(trogiup);
        }

        //
        // GET: /TroGiup/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /TroGiup/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(TroGiup trogiup)
        {
            if (ModelState.IsValid)
            {
                db.TroGiup.Add(trogiup);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(trogiup);
        }

        //
        // GET: /TroGiup/Edit/5

        public ActionResult Edit(int id = 0)
        {
            TroGiup trogiup = db.TroGiup.Find(id);
            if (trogiup == null)
            {
                return HttpNotFound();
            }
            return View(trogiup);
        }

        //
        // POST: /TroGiup/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(TroGiup trogiup)
        {
            if (ModelState.IsValid)
            {
                db.Entry(trogiup).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(trogiup);
        }

        //
        // GET: /TroGiup/Delete/5

        public ActionResult Delete(int id = 0)
        {
            TroGiup trogiup = db.TroGiup.Find(id);
            if (trogiup == null)
            {
                return HttpNotFound();
            }
            return View(trogiup);
        }

        //
        // POST: /TroGiup/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TroGiup trogiup = db.TroGiup.Find(id);
            db.TroGiup.Remove(trogiup);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

FinalProject2/FinalProject2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - My ASP.NET MVC Application</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <img src="~/Images/19984.jpg" style="width:960px;height:300px" />
                    <h2><p class="site-title">@Html.ActionLink("Thay đổi cách quản lí thời gian- Thay đổi cuộc sống của bạn", "Index", "Home")</p></h2>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    <nav>
                        <ul id="menu">
                            @if (Request.IsAuthenticated)
                            {
                                <li>@Html.ActionLink("Trang Chủ", "Index", "TrangChu")</li>
                            }
                            else
                            {
                                <li>@Html.ActionLink("Trang Chủ", "Index", "Home")</li>
                            }

                            <li>@Html.ActionLink("Thông Tin Cá Nhân", "Index", "ThongTinCaNhan")</li>
                            <li>@Html.ActionLink("Công Việc", "Index", "CongViec")</li>
                            <li>@Html.ActionLink("Trợ Giúp", "Index", "TroGiup")</li>
                            <li>@Html.ActionLink("Liên Hệ", "Contact", "Home")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - My ASP.NET MVC Application</p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>

</html>